[build-system]
requires = [
    "setuptools>=61.0",
    "wheel",
    "pybind11>=2.10.0",
    "numpy>=1.21.0"
]
build-backend = "setuptools.build_meta"

[project]
name = "tomo_tv"
version = "1.0.0"
description = "Python and C++ toolbox for tomographic data processing and developing iterative reconstruction algorithms"
readme = "README.md"
requires-python = ">=3.8"
license = {text = "MIT"}
authors = [
    {name = "Jonathan Schwartz", email = "jtschw@umich.edu"}
]
keywords = ["tomography", "reconstruction", "cuda", "imaging", "electron-microscopy"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: C++",
    "Topic :: Scientific/Engineering :: Image Processing",
    "Topic :: Scientific/Engineering :: Medical Science Apps.",
]
dependencies = [
    "numpy>=1.21.0",
    "scipy>=1.7.0",
    "matplotlib>=3.3.0",
    "h5py>=3.0.0",
    "mpi4py>=3.0.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=6.0",
    "pytest-cov",
    "black",
    "flake8",
    "mypy",
]
test = [
    "pytest>=6.0",
    "pytest-cov",
]

[project.urls]
Homepage = "https://github.com/jtschwar/tomo_TV"
Repository = "https://github.com/jtschwar/tomo_TV"
Issues = "https://github.com/jtschwar/tomo_TV/issues"
Documentation = "https://jtschwar.github.io"

[tool.setuptools]
packages = ["tomo_tv"]

[tool.setuptools.package-data]
tomo_tv = ["*.so", "*.dll", "*.dylib"]

# Optional: Configure development tools
[tool.black]
line-length = 88
target-version = ['py38']
